# version: '3'
# services:
#   web:
#     build: .
#     command: python core/server.py
#     volumes:
#       - .:/app
#     ports:
#       - "8080:8080"



version: '3'
services:
  web:
    build: .
    command: python core/server.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"



